// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrnzrKhYQe5qqa4dutC2F6xlegSqBaDwc',
    appId: '1:877593837023:web:bcbd64667ce2dc82b3586a',
    messagingSenderId: '877593837023',
    projectId: 'food-cdb6b',
    authDomain: 'food-cdb6b.firebaseapp.com',
    storageBucket: 'food-cdb6b.firebasestorage.app',
    measurementId: 'G-S6N5CT0GVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkwRBMvbDYRTPDZBrbFIcf5Ld1SYXagX0',
    appId: '1:877593837023:android:13bbd6717e781571b3586a',
    messagingSenderId: '877593837023',
    projectId: 'food-cdb6b',
    storageBucket: 'food-cdb6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnhNlpF2xpcOPwkFvTQ_6bl6DetA97AdI',
    appId: '1:877593837023:ios:3d98e7fc203a8dc9b3586a',
    messagingSenderId: '877593837023',
    projectId: 'food-cdb6b',
    storageBucket: 'food-cdb6b.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnhNlpF2xpcOPwkFvTQ_6bl6DetA97AdI',
    appId: '1:877593837023:ios:3d98e7fc203a8dc9b3586a',
    messagingSenderId: '877593837023',
    projectId: 'food-cdb6b',
    storageBucket: 'food-cdb6b.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrnzrKhYQe5qqa4dutC2F6xlegSqBaDwc',
    appId: '1:877593837023:web:6b4cd33e3d48eb73b3586a',
    messagingSenderId: '877593837023',
    projectId: 'food-cdb6b',
    authDomain: 'food-cdb6b.firebaseapp.com',
    storageBucket: 'food-cdb6b.firebasestorage.app',
    measurementId: 'G-4VCMBR4J44',
  );
}
